services:
  api:
    image: aniketsuryawanshi/tabletalk-be:latest
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      PORT: 3004
      HOST: 0.0.0.0
      NODE_ENV: production
    command: node dist/index.js
